-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.temas
(
    id_tema serial NOT NULL,
    nombre character varying(60) NOT NULL,
    PRIMARY KEY (id_tema)
);

CREATE TABLE IF NOT EXISTS public.libros
(
    "ISBN" character NOT NULL,
    titulo character varying(60) NOT NULL,
    autor character varying(60) NOT NULL,
    "numero de ejemplares" integer NOT NULL,
    id_tema integer NOT NULL,
    PRIMARY KEY ("ISBN")
);

CREATE TABLE IF NOT EXISTS public.socios
(
    id_socio serial NOT NULL,
    nombre character varying(60) NOT NULL,
    edad integer NOT NULL,
    PRIMARY KEY (id_socio)
);

CREATE TABLE IF NOT EXISTS public.prestamo
(
    id_reserva serial,
    fecha_prestamo date NOT NULL,
    "fecha_devolución" date NOT NULL,
    "ISBN" character(20) NOT NULL,
    id_socio serial NOT NULL,
    PRIMARY KEY (id_reserva)
);

ALTER TABLE IF EXISTS public.libros
    ADD CONSTRAINT fk_libros_temas FOREIGN KEY (id_tema)
    REFERENCES public.temas (id_tema) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prestamo
    ADD CONSTRAINT fk_prestamo_libro FOREIGN KEY ("ISBN")
    REFERENCES public.libros ("ISBN") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prestamo
    ADD CONSTRAINT fk_prestamo_socios FOREIGN KEY (id_socio)
    REFERENCES public.socios (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;